# Original from envoyproject/envoy:examples/front-proxy/docker-compose.yml
# Modified by Instana:
# - use instana-opentracing dockerfiles
version: '3'
services:

  client-app:
    build:
      context: ./client-app
    networks:
      - nginxmesh
    environment:
      - INSTANA_DEV=1
      - target_url=http://server-app:8080/zipkin-demo

  server-app:
    build:
      context: ./server-app
    networks:
      nginxmesh:
        aliases:
          - server-app
    environment:  
      - INSTANA_DEV=1
      - SERVER_PORT=8080
    expose:
      - "8080"

  agent:
    image: instana/agent:test
    pid: "host"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev:/dev
      - /sys:/sys
      - /var/log:/var/log
      - ./agent/configuration.yaml:/root/configuration.yaml
    networks:
      nginxmesh:
        aliases:
          - instana-agent
    environment:
      - INSTANA_AGENT_ENDPOINT=${agent_endpoint}
      - INSTANA_AGENT_ENDPOINT_PORT=443
      - INSTANA_AGENT_KEY=${agent_key}
      - INSTANA_AGENT_ZONE=zipkin-dockerized-demo
    expose:
      - "42699"

networks:
  nginxmesh: {}
